# AUR 包自动更新工具配置文件

# 基础设置
settings:
  # 下载设置
  download:
    # 下载重试次数
    max_retries: 3
    # 重试等待时间（秒）
    retry_wait: 1
    # 下载超时时间（秒）
    timeout: 60
    # 每个服务器的最大连接数
    connections: 16
    # 是否显示下载进度
    show_progress: true

# 包配置
packages:
  qq:
    name: qq
    source: qq
    source_url: "https://im.qq.com/linuxqq/index.shtml"
    fetch_url: "https://cdn-go.cn/qq-web/im.qq.com_new/latest/rainbow/linuxConfig.js"
    upstream: "Tencent/QQ"
    parser: QQParser
    pkgbuild: "packages/linuxqq-nt/PKGBUILD"
    update_source_url: true
    enable: true  # 是否启用更新，false 则跳过
    arch:
      - x86_64
      - aarch64
      - loong64

  navicat:
    name: navicat-premium-zh-cn
    source: navicat-premium-cs
    source_url: "https://www.navicat.com.cn/products/navicat-premium"
    fetch_url: "https://www.navicat.com.cn/products/navicat-premium-release-note#L"
    upstream: "PremiumSoft CyberTech Ltd./Navicat Premium"
    parser: NavicatPremiumCSParser
    pkgbuild: "packages/navicat17-premium-zh-cn/PKGBUILD"
    update_source_url: false
    enable: true  # 是否启用更新，false 则跳过
    arch:
      - x86_64
      - aarch64
    urls:
      x86_64: "https://dn.navicat.com/download/navicat17-premium-cs-x86_64.AppImage"
      aarch64: "https://dn.navicat.com/download/navicat17-premium-cs-aarch64.AppImage"

  trae:
    name: trae
    source: trae
    source_url: "https://www.trae.cn/"
    fetch_url: "https://icube-normal.trae.ai/icube/api/v1/native/version/trae/latest"
    upstream: "ByteDance/Trae"
    parser: TraeParser
    pkgbuild: "packages/trae/PKGBUILD"
    update_source_url: true
    enable: true
    arch:
      - x86_64
      - aarch64

  trae-sg:
    name: trae-sg
    source: trae
    source_url: "https://www.trae.cn/"
    fetch_url: "https://icube-normal.trae.ai/icube/api/v1/native/version/trae/latest"
    upstream: "ByteDance/Trae"
    parser: TraeParser_SG
    pkgbuild: "packages/trae-sg/PKGBUILD"
    update_source_url: true
    enable: true
    arch:
      - x86_64
      - aarch64

  trae-us:
    name: trae-us
    source: trae
    source_url: "https://www.trae.cn/"
    fetch_url: "https://icube-normal.trae.ai/icube/api/v1/native/version/trae/latest"
    upstream: "ByteDance/Trae"
    parser: TraeParser_US
    pkgbuild: "packages/trae-us/PKGBUILD"
    update_source_url: true
    enable: true
    arch:
      - x86_64
      - aarch64
